### ISSUE TITLE
utf-8 codec error

### ISSUE THREAD

**Issue by mnwato** [ashalogic/Persian-Sentiment-Analyzer#1]
Hi 
at the first I encourage you for this useful code

I have a problem in loading csv file
your file is OK but when i want to load my csv file I have this kind of error:

![image](https://user-images.githubusercontent.com/39694920/74381012-f293e780-4dff-11ea-8f2c-5067cdbdace5.png)

I think this comes from the way I save xlsx file to csv >> I used CSV (Comma delimited) option and utf-8 for encoding in web option tool .

![image](https://user-images.githubusercontent.com/39694920/74380902-b19bd300-4dff-11ea-888b-c7badd82d6fb.png)

Am I right if not so which way do you use to creat csv file?

thanks in advanecd

**Comment by ashalogic** [comment]
hey, do you speak Persian?
anyway, I need to check your file so upload the first 10 records of your file here then I can debug it.

**Comment by mnwato** [comment]
> hey, do you speak Persian?
> anyway, I need to check your file so upload the first 10 records of your file here then I can debug it.

Yeah. I speak persian, But because it may be a problem of the other one so (trying) to write english.
[dataset.zip](https://github.com/ashalogic/Persian-Sentiment-Analyzer/files/4198540/dataset.zip)

**Comment by mnwato** [comment]
Another question:
If I want to have 3 output for (pos,neg,nat) so which part of the code must be change or which code must add to the code?
thanks

**Comment by fatemehniknezhad** [comment]
> 

hi, after loading data in code, with adding if else condition for rate, you can replace label to neg,nat,pos.

**Comment by mnwato** [comment]
Hi. Thank you.
This issue was for 2 years ago which i was started to learn nlp.
I forgot i close it.
